 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/information_provisions", type: :request do
  # InformationProvision. As you add validations to InformationProvision, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      InformationProvision.create! valid_attributes
      get information_provisions_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      information_provision = InformationProvision.create! valid_attributes
      get information_provision_url(information_provision)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_information_provision_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      information_provision = InformationProvision.create! valid_attributes
      get edit_information_provision_url(information_provision)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new InformationProvision" do
        expect {
          post information_provisions_url, params: { information_provision: valid_attributes }
        }.to change(InformationProvision, :count).by(1)
      end

      it "redirects to the created information_provision" do
        post information_provisions_url, params: { information_provision: valid_attributes }
        expect(response).to redirect_to(information_provision_url(InformationProvision.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new InformationProvision" do
        expect {
          post information_provisions_url, params: { information_provision: invalid_attributes }
        }.to change(InformationProvision, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post information_provisions_url, params: { information_provision: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested information_provision" do
        information_provision = InformationProvision.create! valid_attributes
        patch information_provision_url(information_provision), params: { information_provision: new_attributes }
        information_provision.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the information_provision" do
        information_provision = InformationProvision.create! valid_attributes
        patch information_provision_url(information_provision), params: { information_provision: new_attributes }
        information_provision.reload
        expect(response).to redirect_to(information_provision_url(information_provision))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        information_provision = InformationProvision.create! valid_attributes
        patch information_provision_url(information_provision), params: { information_provision: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested information_provision" do
      information_provision = InformationProvision.create! valid_attributes
      expect {
        delete information_provision_url(information_provision)
      }.to change(InformationProvision, :count).by(-1)
    end

    it "redirects to the information_provisions list" do
      information_provision = InformationProvision.create! valid_attributes
      delete information_provision_url(information_provision)
      expect(response).to redirect_to(information_provisions_url)
    end
  end
end
